export const CHANGE_INTERNALLY_TOURIST_INFO = 'CHANGE_INTERNALLY_TOURIST_INFO';
export const CREATE_TOURIST_CARD = 'CREATE_TOURIST_CARD';
export const GET_ERROR_DURING_UPDATE = 'GET_ERROR_DURING_UPDATE';
export const FIND_TOURIST = 'FIND_TOURIST';
export const RESET_TOURIST_CARD_DATA = 'RESET_TOURIST_CARD_DATA';
export const SAVE_TOURIST_CARD_INFO_SUCCESSFULLY = 'SAVE_TOURIST_CARD_INFO_SUCCESSFULLY';
export const SET_INITIAL_DEPARTMENTS = 'SET_INITIAL_DEPARTMENTS';
export const TURN_ON_TOURIST_CARD_CREATION = 'TURN_ON_TOURIST_CARD_CREATION';
